# Data Science Foundations – Day 1

 Objective:
 - Understand Jupyter workflow
 - Run Python commands
 - Import NumPy
 - Perform simple calculations

In [8]:
print("Hello, Data Science World!")

Hello, Data Science World!


In [9]:
2+3

5

In [10]:
10*5

50

In [11]:
100/4

25.0

In [12]:
#Create Variable

a = 10
b = 5

a + b

15

In [13]:
#Import Numpy
import numpy as np

In [14]:
#Create a numpy Array

arr = np.array([10, 20, 30, 40, 50])

arr

array([10, 20, 30, 40, 50])

In [15]:
arr*2

array([ 20,  40,  60,  80, 100])

In [17]:
arr.sum()


np.int64(150)

In [18]:
arr.mean()


np.float64(30.0)

In [19]:

arr.max()

np.int64(50)

In [20]:
#2D Array (Very Important for ML)

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
matrix.shape

(2, 3)

In [24]:
#Notebook-Based Data Exploration
import pandas as pd

df = pd.read_csv("Matches.csv")
df.head()
df.shape
df.info()
df.describe()
df.isnull().sum()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 636 entries, 0 to 635
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   id               636 non-null    int64  
 1   season           636 non-null    int64  
 2   city             629 non-null    object 
 3   date             636 non-null    object 
 4   team1            636 non-null    object 
 5   team2            636 non-null    object 
 6   toss_winner      636 non-null    object 
 7   toss_decision    636 non-null    object 
 8   result           636 non-null    object 
 9   dl_applied       636 non-null    int64  
 10  winner           633 non-null    object 
 11  win_by_runs      636 non-null    int64  
 12  win_by_wickets   636 non-null    int64  
 13  player_of_match  633 non-null    object 
 14  venue            636 non-null    object 
 15  umpire1          635 non-null    object 
 16  umpire2          635 non-null    object 
 17  umpire3         

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
