In [25]:
import numpy as np

prices=np.array([100,200,300,400,500])
prices=prices*1.10
print(prices)
arr=np.array([[10,20,30],
              [40,50,60]])
arr=arr+5
print(arr)

[110. 220. 330. 440. 550.]
[[15 25 35]
 [45 55 65]]


In [26]:
arr=np.array([10,20,30,40,50])
arr[1]


np.int64(20)

In [27]:
arr[1:4]

array([20, 30, 40])

In [28]:
sales_day1=np.array([120,85,60])
sales_day2=np.array([150,90,75])
total_sales=sales_day1+sales_day2
print(total_sales)
percentage_growth=((sales_day2-sales_day1)/sales_day1)*100
print(percentage_growth)
highest_growth=np.argmax(percentage_growth)
if highest_growth==0:
    print("Highest Growth=A")
elif highest_growth==1:
    print("Highest Growth=B")
else:
    print("Highest Growth=C")



[270 175 135]
[25.          5.88235294 25.        ]
Highest Growth=A


In [29]:
temps=np.array([[25,28,30],
                [22,24,26],
                [30,32,33],
                [27,29,31],
                [20,21,23]])
temps2=(temps*(9/5))+32
print(temps2)
correction=np.array([1,-1,0])
adjusted=temps+correction
print(adjusted)

[[77.  82.4 86. ]
 [71.6 75.2 78.8]
 [86.  89.6 91.4]
 [80.6 84.2 87.8]
 [68.  69.8 73.4]]
[[26 27 30]
 [23 23 26]
 [31 31 33]
 [28 28 31]
 [21 20 23]]


In [30]:
bp=np.array([[120,80],
             [135,85],
             [140,90],
             [110,70],
             [125,75]])
systolic=bp[:,0]
print(systolic)
high_bp=bp[bp[:,0]>130]
print("High BP:")
print(high_bp)
print("Replaced values:")
bp[bp[:,1]<80,1]=80
print(bp)


[120 135 140 110 125]
High BP:
[[135  85]
 [140  90]]
Replaced values:
[[120  80]
 [135  85]
 [140  90]
 [110  80]
 [125  80]]


In [31]:
yields=np.array([[2.5,3.0,1.0],
                 [2.8,3.2,2.0],
                 [3.1,2.9,2.2],
                 [2.6,3.1,1.9]])
yields[1]=yields[1]+np.array([0.2,0.3,0.1])
print("Value added to second region")
print(yields)
yields[:,2]=yields[:,2]*1.1
print("Multiply Coulmn C by 1.1")
print(yields)
avg=np.mean(yields,axis=0)
print("highest Average yield:",np.argmax(avg))


Value added to second region
[[2.5 3.  1. ]
 [3.  3.5 2.1]
 [3.1 2.9 2.2]
 [2.6 3.1 1.9]]
Multiply Coulmn C by 1.1
[[2.5  3.   1.1 ]
 [3.   3.5  2.31]
 [3.1  2.9  2.42]
 [2.6  3.1  2.09]]
highest Average yield: 1


In [32]:
scores=np.array([[85,78,92],
         [88,74,90],
         [70,65,80],
         [95,89,96]
         ])
top_two=scores[:2]
print("Top Two Students:")
print(top_two)
math=scores[:,0]
print("Maths Scores:",math)
science=scores[scores[:,2]>90]
print("High Scores in science:",science)

Top Two Students:
[[85 78 92]
 [88 74 90]]
Maths Scores: [85 88 70 95]
High Scores in science: [[85 78 92]
 [95 89 96]]


In [33]:
matrix=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]
                 ])
matrix[0]
matrix[:,1]
matrix[1:,0:2]

array([[4, 5],
       [7, 8]])

In [34]:
crops=np.array([[9000,5600,780,890],
               [7800,6500,468,7674],
               [560,877,655,2500],
               ])
crops=crops*1.10
print("Yield increased by 10%:",crops)
print("Wheat's yield:", crops[0])
print("Average yield per crop accross all seasons:",np.mean(crops,axis=1))
print("Yields greater than 3000:",crops[crops>3000])


Yield increased by 10%: [[9900.  6160.   858.   979. ]
 [8580.  7150.   514.8 8441.4]
 [ 616.   964.7  720.5 2750. ]]
Wheat's yield: [9900. 6160.  858.  979.]
Average yield per crop accross all seasons: [4474.25 6171.55 1262.8 ]
Yields greater than 3000: [9900.  6160.  8580.  7150.  8441.4]


In [35]:
import numpy as np

# Create 2D array
production = np.array([
    [450, 520, 480, 500],   # Gadgets
    [300, 350, 400, 380],   # Tools
    [600, 650, 700, 720]    # Machines
])

print("Original Production Data:\n", production)
production_updated = production * 1.05
print("After 5% Increase:\n", production_updated)
gadgets = production_updated[0]
print("Gadgets Production:", gadgets)
average_production = np.mean(production_updated, axis=1)
print("Average Production per Product:", average_production)
high_production = production_updated[production_updated > 500]
print("Production values greater than 500:\n", high_production)

Original Production Data:
 [[450 520 480 500]
 [300 350 400 380]
 [600 650 700 720]]
After 5% Increase:
 [[472.5 546.  504.  525. ]
 [315.  367.5 420.  399. ]
 [630.  682.5 735.  756. ]]
Gadgets Production: [472.5 546.  504.  525. ]
Average Production per Product: [511.875 375.375 700.875]
Production values greater than 500:
 [546.  504.  525.  630.  682.5 735.  756. ]


In [36]:
import pandas as pd

data = {
    "Name":["A","B","C"],
    "Salary":[50000,60000,55000]
}
df=pd.DataFrame(data)
print(df)

  Name  Salary
0    A   50000
1    B   60000
2    C   55000


In [37]:
type(df["Salary"])

pandas.core.series.Series

In [41]:
import pandas as pd
df=pd.read_csv("Matches.csv")
df.head()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 636 entries, 0 to 635
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   id               636 non-null    int64  
 1   season           636 non-null    int64  
 2   city             629 non-null    object 
 3   date             636 non-null    object 
 4   team1            636 non-null    object 
 5   team2            636 non-null    object 
 6   toss_winner      636 non-null    object 
 7   toss_decision    636 non-null    object 
 8   result           636 non-null    object 
 9   dl_applied       636 non-null    int64  
 10  winner           633 non-null    object 
 11  win_by_runs      636 non-null    int64  
 12  win_by_wickets   636 non-null    int64  
 13  player_of_match  633 non-null    object 
 14  venue            636 non-null    object 
 15  umpire1          635 non-null    object 
 16  umpire2          635 non-null    object 
 17  umpire3         

,id,season,dl_applied,win_by_runs,win_by_wickets,umpire3
count,636.000000,636.000000,636.000000,636.000000,636.000000,0.0
mean,318.500000,2012.490566,0.025157,13.682390,3.372642,NaN
std,183.741666,2.773026,0.156726,23.908877,3.420338,NaN
min,1.000000,2008.000000,0.000000,0.000000,0.000000,NaN
25%,159.750000,2010.000000,0.000000,0.000000,0.000000,NaN
50%,318.500000,2012.000000,0.000000,0.000000,4.000000,NaN
75%,477.250000,2015.000000,0.000000,20.000000,7.000000,NaN
max,636.000000,2017.000000,1.000000,146.000000,10.000000,NaN
